version: "3.3"

services:

  rabbitmq:
    image: rabbitmq:3.5
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "23181:23181"
      - "15671:15671"
    configs:
      - source: rabbitmq_rabbitmq.config
        target: /etc/rabbitmq/rabbitmq.config
      - source: rabbitmq_enabled_plugins
        target: /etc/rabbitmq/enabled_plugins
      - source: rabbitmq_definitions.json
        target: /etc/rabbitmq/definitions.json
    secrets:
      - waggle_cacert
      - waggle_rabbitmq_cert
      - waggle_rabbitmq_key
    environment:
      - RABBITMQ_NODENAME=rabbitmq@rabbitmq
      - RABBITMQ_ERLANG_COOKIE=supercookie
    volumes:
      - data_rabbitmq:/var/lib/rabbitmq
    networks:
    - overlay

  cassandra:
    image: cassandra:3.2
    ports:
      - "9042:9042"
    volumes:
      - data_cassandra:/var/lib/cassandra
    networks:
    - overlay

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=waggle
      - MYSQL_DATABASE=waggle
      - MYSQL_USER=waggle
      - MYSQL_PASSWORD=waggle
    ports:
      - "3306:3306"
    volumes:
      - data_mysql:/var/lib/mysql
    networks:
    - overlay

  loader_raw:
    image: waggle/beehive-loader-raw
    networks:
    - overlay

  loader_decoded:
    image: waggle/beehive-loader-decoded
    networks:
    - overlay

  worker_alphasense:
    image: waggle/beehive-worker-alphasense
    networks:
    - overlay

  worker_coresense:
    image: waggle/beehive-worker-coresense
    networks:
    - overlay

  worker_gps:
    image: waggle/beehive-worker-gps-sense
    networks:
    - overlay

configs:
  rabbitmq_rabbitmq.config:
    file: ./beehive-rabbitmq/configs/rabbitmq.config.stack
  rabbitmq_enabled_plugins:
    file: ./beehive-rabbitmq/configs/enabled_plugins
  rabbitmq_definitions.json:
    file: ./beehive-rabbitmq/configs/definitions.json

secrets:
  waggle_cacert:
    external: true
  waggle_rabbitmq_cert:
    external: true
  waggle_rabbitmq_key:
    external: true

volumes:
  data_rabbitmq:
  data_cassandra:
  data_mysql:

networks:
  overlay:
