version: "3.3"

services:
  rabbitmq:
    image: rabbitmq:3.5
    ports:
      - "127.0.0.1:5672:5672"
      - "23181:23181"
      - "15671:15671"
    configs:
      - source: rabbitmq_rabbitmq.config
        target: /etc/rabbitmq/rabbitmq.config
      - source: rabbitmq_enabled_plugins
        target: /etc/rabbitmq/enabled_plugins
      - source: rabbitmq_definitions.json
        target: /etc/rabbitmq/definitions.json
    secrets:
      - waggle_cacert
      - waggle_rabbitmq_cert
      - waggle_rabbitmq_key
      # specify rabbitmq cookie as secret
    hostname: rabbitmq
    environment:
      - RABBITMQ_NODENAME=rabbitmq@rabbitmq
    volumes:
      - data_rabbitmq:/var/lib/rabbitmq

  cassandra:
    image: cassandra:3.2
    hostname: cassandra
    ports:
      - "127.0.0.1:9042:9042"
    volumes:
      - data_cassandra:/var/lib/cassandra

  mysql:
    image: mysql:5.7
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=waggle
      - MYSQL_DATABASE=waggle
      - MYSQL_USER=waggle
      - MYSQL_PASSWORD=waggle
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - data_mysql:/var/lib/mysql

  loader_raw:
    image: waggle/beehive-loader-raw

  loader:
    image: waggle/beehive-loader

  loader_decoded:
    image: waggle/beehive-loader-decoded

  worker_alphasense:
    image: waggle/beehive-worker-alphasense

  worker_coresense:
    image: waggle/beehive-worker-coresense

  worker_gps:
    image: waggle/beehive-worker-gps-sense

configs:
  rabbitmq_rabbitmq.config:
    file: ./beehive-rabbitmq/configs/rabbitmq.config.stack
  rabbitmq_enabled_plugins:
    file: ./beehive-rabbitmq/configs/enabled_plugins
  rabbitmq_definitions.json:
    file: ./beehive-rabbitmq/configs/definitions.json

secrets:
  waggle_cacert:
    external: true
  waggle_rabbitmq_cert:
    external: true
  waggle_rabbitmq_key:
    external: true

volumes:
  data_rabbitmq:
  data_cassandra:
  data_mysql:
