version: '3.3'
services:
  worker_alphasense:
    image: waggle/beehive-worker-alphasense
  worker_coresense:
    image: waggle/beehive-worker-coresense
  worker_gps:
    image: waggle/beehive-worker-gps
